"""
figures/fig06_flight_covariates/plot_flight_covariates.py
=========================================================
Figure 6 — Flight-level covariates and their Spearman correlation with
per-flight absolute error (|MAE|) for the EVA-02-B model under CV0.

The figure is a horizontal bar chart; each bar represents one covariate's
Spearman ρ against per-flight |MAE|.  An additional scatter-grid is saved for
exploratory use (not the primary manuscript figure).

Data sources
------------
    Predictions  : results/eva02_base/predictions/cv0_combined_predictions.csv
                   Required columns: image_filename, actual, predicted, fold

    Covariates   : data/covariates/flight_covariates.csv
                   Pre-joined flight-level features.  Required columns:
                     flight_key          — "YYYYMMDD_FIELD" (e.g. "20230713_G3")
                     sza                 — solar zenith angle (°)
                     solar_noon_abs_min  — |minutes from solar noon|
                     solar_noon_min      — signed minutes from solar noon
                     shadow_row_angle    — sun-to-row-direction angle (°)
                     dpi                 — days post-inoculation
                     agdd               — accumulated GDD (base 50 °F)
                     irradiance_mean    — mean irradiance (W m⁻²)
                     irradiance_cv      — coefficient of variation of irradiance
                     score_flight_offset_abs    — |days| between scoring and flight
                     score_flight_offset_signed — signed offset (flight − scoring)

    The flight_covariates.csv is generated by the data-preparation workflow
    documented in data/data_README.md.  Run that workflow before this script.

Outputs (written to the same directory as this script)
------------------------------------------------------
    fig06_flight_covariates.{pdf,png}      — primary manuscript figure (bar chart)
    fig06_flight_covariates_scatter.{pdf,png} — supplemental scatter grid
    fig06_flight_covariates_stats.csv      — Spearman ρ, p-value, n per covariate

Usage
-----
    # From repo root:
    python figures/fig06_flight_covariates/plot_flight_covariates.py

    # Override default paths:
    python figures/fig06_flight_covariates/plot_flight_covariates.py \\
        --predictions results/eva02_base/predictions/cv0_combined_predictions.csv \\
        --covariates  data/covariates/flight_covariates.csv
"""

from __future__ import annotations

import argparse
import re
import sys
import warnings
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd
from scipy import stats

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Shared style
# ---------------------------------------------------------------------------
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from style import apply_style, despine, save_fig

apply_style()

# ---------------------------------------------------------------------------
# Repository paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent.parent

PREDICTIONS_DEFAULT = (
    ROOT / "experiments" / "eva02_base_cv0" / "predictions" / "cv0_combined_predictions.csv"
)
COVARIATES_DEFAULT  = ROOT / "data" / "covariates" / "flight_covariates.csv"
OUTPUT_DIR          = Path(__file__).resolve().parent

# ---------------------------------------------------------------------------
# Covariate specifications
# ---------------------------------------------------------------------------
# COVARIATES_MAE  — used for the primary bar chart (|MAE| vs covariate)
# COVARIATES_SIGNED — used for supplemental scatter (signed error vs covariate)
#
# Each entry is (column_name, axis_label_string).
# Column names must match those in flight_covariates.csv.
COVARIATES_MAE: list[tuple[str, str]] = [
    ("sza",                     "Solar zenith angle (°)"),
    ("abs_time_from_noon",      "|Time from solar noon| (min)"),
    ("dpi",                     "Days post-inoculation"),
    ("agdd",                    "Accum. GDD (base 50 °F)"),
    ("irradiance_mean",         "Irradiance mean (W m⁻²)"),
    ("irradiance_cv",           "Irradiance CV"),
    ("shadow_row_angle",        "Shadow–row angle (°)"),
]

COVARIATES_SIGNED: list[tuple[str, str]] = [
    ("sza",                        "Solar zenith angle (°)"),
    ("abs_time_from_noon",             "Time from solar noon (min, signed)"),
    ("dpi",                        "Days post-inoculation"),
    ("agdd",                       "Accum. GDD (base 50 °F)"),
    ("irradiance_mean",            "Irradiance mean (W m⁻²)"),
    ("irradiance_cv",              "Irradiance CV"),
    ("shadow_row_angle",           "Shadow–row angle (°)"),
]

# Bar color: use a single neutral dark color for the horizontal bars; the
# signed direction (positive / negative ρ) provides the visual encoding.
BAR_COLOR_POS = "#D29343"   # batlow-171 — negative ρ
BAR_COLOR_NEG = "#1C5A62"   # batlow-58 — positive ρ

# ---------------------------------------------------------------------------
# Covariate categories (for the supplemental table)
# ---------------------------------------------------------------------------
COVARIATE_CATEGORIES: dict[str, str] = {
    "irradiance_mean":    "Lighting",
    "irradiance_cv":      "Lighting",
    "sza":                "Solar geometry",
    "abs_time_from_noon": "Solar geometry",
    "shadow_row_angle":   "Solar geometry",
    "agdd":               "Temporality",
    "dpi":                "Temporality",
}


# ---------------------------------------------------------------------------
# Data loading and preprocessing
# ---------------------------------------------------------------------------

_FLIGHT_KEY_RE = re.compile(r"(\d{8})_([A-Za-z0-9]+)_")

def _extract_flight_key(filename: str) -> str | None:
    """
    Parse 'YYYYMMDD_FIELD' from an image filename.

    Filename convention: YYYYMMDD_FIELD_PLOTNUMBER.jpg
    Example: '20230713_G3_09565.jpg'  →  '20230713_G3'
    """
    m = _FLIGHT_KEY_RE.match(str(filename))
    return f"{m.group(1)}_{m.group(2).upper()}" if m else None


def compute_flight_mae(pred_path: Path) -> pd.DataFrame:
    """
    Aggregate per-image predictions to per-flight |MAE| and mean signed error.

    Parameters
    ----------
    pred_path : path to cv0_combined_predictions.csv

    Returns
    -------
    DataFrame with columns: flight_key, mae, mean_error
    """
    df = pd.read_csv(pred_path)
    df.columns = [c.strip().lower() for c in df.columns]

    # Compute signed_error if not already present
    if "signed_error" not in df.columns:
        df["signed_error"] = df["predicted"] - df["actual"]
    df["abs_error"] = df["signed_error"].abs()

    # Parse flight_key from image_filename
    df["flight_key"] = df["image_filename"].map(_extract_flight_key)
    df = df.dropna(subset=["flight_key"])

    # Aggregate to flight level
    flight_df = (
        df.groupby("flight_key")
        .agg(mae=("abs_error", "mean"), mean_error=("signed_error", "mean"))
        .reset_index()
    )
    print(f"[predictions] {len(flight_df)} flights  |  "
          f"MAE range {flight_df['mae'].min():.3f}–{flight_df['mae'].max():.3f}")
    return flight_df


def load_and_merge(pred_path: Path, cov_path: Path) -> pd.DataFrame:
    """
    Load and merge flight-level predictions with pre-computed covariates.

    The merge is performed on flight_key (YYYYMMDD_FIELD).  Rows without a
    matching covariate entry are retained but will have NaN for that covariate.

    Returns
    -------
    Merged DataFrame containing mae, mean_error, and all covariate columns.
    """
    flight_mae = compute_flight_mae(pred_path)

    cov = pd.read_csv(cov_path)
    cov.columns = [c.strip().lower() for c in cov.columns]
    print(f"[covariates] {len(cov)} flight rows loaded from {cov_path.name}")

    merged = flight_mae.merge(cov, on="flight_key", how="left")
    print(f"[merged]     {len(merged)} flights after join")
    return merged


# ---------------------------------------------------------------------------
# Spearman correlation
# ---------------------------------------------------------------------------

def _sig_stars(pval: float) -> str:
    """Return significance asterisks for a p-value."""
    if np.isnan(pval):
        return ""
    if pval < 0.001:
        return "***"
    if pval < 0.01:
        return "**"
    if pval < 0.05:
        return "*"
    return "ns"


def compute_spearman(
    df: pd.DataFrame,
    error_col: str,
    covariate_list: list[tuple[str, str]],
) -> pd.DataFrame:
    """
    Compute Spearman ρ and two-sided p-value for each covariate vs *error_col*.

    Parameters
    ----------
    df             : merged flight-level DataFrame
    error_col      : "mae" or "mean_error"
    covariate_list : list of (column_name, label) tuples

    Returns
    -------
    DataFrame with columns: covariate, label, rho, pval, n, stars
    """
    rows = []
    for col, label in covariate_list:
        if col not in df.columns:
            print(f"  [skip] column '{col}' not found — check flight_covariates.csv")
            continue
        sub = df[[error_col, col]].dropna()
        n   = len(sub)
        if n >= 3:
            rho, pval = stats.spearmanr(sub[error_col], sub[col])
        else:
            rho, pval = np.nan, np.nan
        rows.append({
            "covariate": col,
            "label":     label,
            "rho":       rho,
            "pval":      pval,
            "n":         n,
            "stars":     _sig_stars(pval),
        })
        print(f"  {label:<42s}  ρ={rho:+.3f}  p={pval:.4e}  n={n}")
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Figure 6 — horizontal bar chart (primary manuscript figure)
# ---------------------------------------------------------------------------

def plot_bar_chart(corr_df: pd.DataFrame, out_dir: Path, stem: str) -> None:
    """
    Horizontal bar chart of Spearman ρ (per-flight |MAE| vs each covariate).

    Bars are colored by sign of ρ; significance stars are annotated.

    Parameters
    ----------
    corr_df  : DataFrame from compute_spearman()
    out_dir  : output directory
    stem     : filename stem (e.g. "fig06_flight_covariates")
    """
    df = corr_df.dropna(subset=["rho", "pval"]).copy()
    df = df.sort_values("rho")          # ascending so strongest negative is bottom

    n_rows = len(df)
    fig, ax = plt.subplots(figsize=(10, 0.75 * n_rows + 1.8))

    colors = [BAR_COLOR_NEG if r < 0 else BAR_COLOR_POS for r in df["rho"]]
    ax.barh(range(n_rows), df["rho"], color=colors,
            edgecolor="black", linewidth=0.6, height=0.65)

    # Annotate each bar with ρ, significance stars, and n
    max_abs = df["rho"].abs().max() if len(df) else 0.3
    for i, (_, row) in enumerate(df.iterrows()):
        if np.isnan(row["rho"]):
            continue
        x_pos  = row["rho"] + (0.02 if row["rho"] >= 0 else -0.02)
        ha     = "left" if row["rho"] >= 0 else "right"
        label  = f"ρ = {row['rho']:+.3f} p = {row['pval']:.3f}"
        ax.text(x_pos, i, label, va="center", ha=ha, fontsize=9)

    ax.set_yticks(range(n_rows))
    ax.set_yticklabels(df["label"], fontsize=10)
    ax.axvline(0, color="black", linewidth=0.9, linestyle="--")
    ax.set_xlabel("Spearman ρ  (per-flight |MAE| vs flight conditions)", fontsize=11, fontweight="bold")
    ax.spines["left"].set_linewidth(1.5)
    ax.spines["bottom"].set_linewidth(1.5)

    # x-axis limits with enough margin for annotations
    margin = max_abs * 0.55
    ax.set_xlim(-(max_abs + margin), max_abs + margin)
    ax.xaxis.set_major_formatter(mticker.FormatStrFormatter("%.2f"))
    ax.grid(axis="x", alpha=0.3, linestyle="--")
    despine(ax)
    fig.tight_layout()
    save_fig(fig, out_dir, stem)


# ---------------------------------------------------------------------------
# Supplemental scatter grid (exploratory; not the primary figure)
# ---------------------------------------------------------------------------

def plot_scatter_grid(
    df: pd.DataFrame,
    corr_df: pd.DataFrame,
    error_col: str,
    out_dir: Path,
    stem: str,
    covariate_list: list[tuple[str, str]],
) -> None:
    """
    Grid of scatter plots: per-flight error vs each covariate with OLS line.

    Parameters
    ----------
    df             : merged flight-level DataFrame
    corr_df        : Spearman correlation table from compute_spearman()
    error_col      : "mae" or "mean_error"
    out_dir        : output directory
    stem           : filename stem
    covariate_list : list of (column, label) tuples to plot
    """
    valid = [(col, lbl) for col, lbl in covariate_list if col in df.columns]
    if not valid:
        print("[scatter] no valid covariates — skipped")
        return

    corr_lookup = corr_df.set_index("covariate").to_dict("index") if len(corr_df) else {}

    n_cols = 3
    n_rows = int(np.ceil(len(valid) / n_cols))
    fig, axes = plt.subplots(n_rows, n_cols,
                             figsize=(5 * n_cols, 4 * n_rows),
                             squeeze=False)

    y_label = "|MAE| (per flight)" if error_col == "mae" else "Mean signed residual (per flight)"

    for idx, (col, label) in enumerate(valid):
        ax  = axes[idx // n_cols][idx % n_cols]
        sub = df[[error_col, col]].dropna()
        x, y = sub[col].values, sub[error_col].values

        ax.scatter(x, y, s=55, alpha=0.75, color="#3C6D56",
                   edgecolors="white", linewidths=0.4, zorder=3)

        # Horizontal reference at zero for signed error
        if error_col != "mae":
            ax.axhline(0, color="gray", linewidth=0.8, linestyle="--", zorder=2)

        # OLS trend line
        if len(x) >= 2:
            m, b = np.polyfit(x, y, 1)
            x_line = np.linspace(x.min(), x.max(), 200)
            ax.plot(x_line, m * x_line + b, color="#D29343",
                    linewidth=1.5, zorder=4)

        # Spearman ρ annotation
        if col in corr_lookup:
            r = corr_lookup[col]
            rho, pval, n = r["rho"], r["pval"], int(r["n"])
            if not np.isnan(rho):
                ann = f"ρ={rho:+.3f}  p={pval:.3f}  n={n}"
                ax.text(0.04, 0.96, ann, transform=ax.transAxes,
                        fontsize=8, va="top", ha="left",
                        bbox=dict(boxstyle="round,pad=0.3",
                                  fc="white", ec="lightgray", alpha=0.85))

        ax.set_xlabel(label, fontsize=9)
        ax.set_ylabel(y_label if idx % n_cols == 0 else "", fontsize=9)
        ax.grid(alpha=0.25, linestyle="--")
        despine(ax)

    # Hide unused subplot panels
    for idx in range(len(valid), n_rows * n_cols):
        axes[idx // n_cols][idx % n_cols].set_visible(False)

    fig.tight_layout()
    save_fig(fig, out_dir, stem)


# ---------------------------------------------------------------------------
# Supplemental table
# ---------------------------------------------------------------------------

def _spearman_ci(rho: float, n: int, alpha: float = 0.05) -> tuple[float, float]:
    """
    95 % confidence interval for Spearman ρ via Fisher's z-transform.

    Returns (lower, upper).  Returns (nan, nan) when n < 4.
    """
    if np.isnan(rho) or n < 4:
        return np.nan, np.nan
    z     = np.arctanh(np.clip(rho, -0.9999, 0.9999))
    se    = 1.0 / np.sqrt(n - 3)
    z_crit = stats.norm.ppf(1 - alpha / 2)
    return float(np.tanh(z - z_crit * se)), float(np.tanh(z + z_crit * se))


def save_supplemental_table(
    corr_df: pd.DataFrame,
    merged_df: pd.DataFrame,
    out_dir: Path,
    stem: str = "tableS_flight_covariates",
    alpha: float = 0.05,
) -> None:
    """
    Build a full-precision supplemental table (CSV + styled PDF/PNG) summarising
    Spearman ρ, 95 % CI, p-value, covariate mean ± SD, and significance for
    the per-flight |MAE| analysis.

    Columns
    -------
    Covariate | Category | Spearman ρ | p-value | 95 % CI | Mean ± SD | Significant?

    Parameters
    ----------
    corr_df   : output of compute_spearman() for the |MAE| analysis
    merged_df : merged flight-level DataFrame (for mean/SD of each covariate)
    out_dir   : destination directory
    stem      : filename stem
    alpha     : significance threshold (default 0.05)
    """
    rows = []
    for _, r in corr_df.iterrows():
        col   = r["covariate"]
        rho   = r["rho"]
        pval  = r["pval"]
        n     = int(r["n"])
        lo, hi = _spearman_ci(rho, n, alpha=alpha)

        cov_vals = merged_df[col].dropna() if col in merged_df.columns else pd.Series([], dtype=float)
        mean_val = cov_vals.mean()
        sd_val   = cov_vals.std(ddof=1)

        rows.append({
            "Covariate":        r["label"],
            "Category":         COVARIATE_CATEGORIES.get(col, ""),
            "Spearman ρ":       rho,
            "p-value":          pval,
            "95 % CI":          f"[{lo:.3f}, {hi:.3f}]" if not np.isnan(lo) else "—",
            "Mean ± SD":        f"{mean_val:.2f} ± {sd_val:.2f}" if not np.isnan(mean_val) else "—",
            "Significant?":     "Yes" if (not np.isnan(pval) and pval < alpha) else "No",
            # keep full precision for the CSV
            "_rho_full":        rho,
            "_pval_full":       pval,
            "_ci_lo":           lo,
            "_ci_hi":           hi,
            "_mean":            mean_val,
            "_sd":              sd_val,
            "_n":               n,
        })

    tbl = pd.DataFrame(rows)

    # ── CSV (full precision) ─────────────────────────────────────────────────
    csv_cols = [
        "Covariate", "Category",
        "_rho_full", "_pval_full", "_ci_lo", "_ci_hi",
        "_mean", "_sd", "_n", "Significant?",
    ]
    csv_df = tbl[csv_cols].rename(columns={
        "_rho_full":  "Spearman_rho",
        "_pval_full": "p_value",
        "_ci_lo":     "CI_lower_95",
        "_ci_hi":     "CI_upper_95",
        "_mean":      "covariate_mean",
        "_sd":        "covariate_sd",
        "_n":         "n",
    })
    out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = out_dir / f"{stem}.csv"
    csv_df.to_csv(csv_path, index=False, float_format="%.5f")
    print(f"[table] CSV saved → {csv_path}")

    # ── Styled matplotlib table ──────────────────────────────────────────────
    display_cols = ["Covariate", "Category", "Spearman ρ", "p-value",
                    "95 % CI", "Mean ± SD", "Significant?"]

    # Format numeric columns for display
    disp = tbl[display_cols].copy()
    disp["Spearman ρ"] = tbl["_rho_full"].map(
        lambda v: f"{v:+.3f}" if not np.isnan(v) else "—"
    )
    disp["p-value"] = tbl["_pval_full"].map(
        lambda v: f"{v:.4f}" if not np.isnan(v) else "—"
    )

    n_rows, n_cols = disp.shape
    col_widths = [0.26, 0.13, 0.10, 0.09, 0.14, 0.15, 0.10]  # relative widths
    fig_width  = 14
    fig_height = 0.55 * (n_rows + 1) + 0.8

    fig, ax = plt.subplots(figsize=(fig_width, fig_height))
    ax.set_axis_off()

    header_color = "#1C5A62"
    row_colors   = [["#f0f4f4" if i % 2 == 0 else "white"] * n_cols
                    for i in range(n_rows)]

    table = ax.table(
        cellText=disp.values,
        colLabels=display_cols,
        cellLoc="center",
        loc="center",
        colWidths=col_widths,
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9)

    # Style header
    for j in range(n_cols):
        cell = table[0, j]
        cell.set_facecolor(header_color)
        cell.set_text_props(color="white", fontweight="bold")
        cell.set_edgecolor("white")
        cell.set_height(0.12)

    # Style data rows
    for i in range(n_rows):
        bg = "#f0f4f4" if i % 2 == 0 else "white"
        sig = disp.iloc[i]["Significant?"]
        for j in range(n_cols):
            cell = table[i + 1, j]
            cell.set_facecolor(bg)
            cell.set_edgecolor("#dddddd")
            cell.set_height(0.10)
            # Bold and slightly tinted for significant rows
            if sig == "Yes":
                cell.set_text_props(fontweight="bold")

    # Left-align the covariate and category columns
    for i in range(n_rows):
        table[i + 1, 0].get_text().set_ha("left")
        table[i + 1, 0].PAD = 0.02
        table[i + 1, 1].get_text().set_ha("left")

    ax.set_title(
        "Table S__ — Spearman correlations: per-flight |MAE| vs flight-level covariates\n"
        f"(EVA-02-B model, CV0; n = flights; α = {alpha})",
        fontsize=10, fontweight="bold", pad=12, loc="left",
    )

    fig.tight_layout()
    save_fig(fig, out_dir, stem)
    print(f"[table] figure saved → {out_dir / stem}")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Figure 6 — Spearman correlations: flight-level |MAE| vs covariates.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--predictions", default=str(PREDICTIONS_DEFAULT),
                        help="Combined CV0 predictions CSV.")
    parser.add_argument("--covariates",  default=str(COVARIATES_DEFAULT),
                        help="Pre-joined flight covariate CSV.")
    parser.add_argument("--out_dir",     default=str(OUTPUT_DIR),
                        help="Output directory for figures and CSV.")
    args = parser.parse_args()

    pred_path = Path(args.predictions)
    cov_path  = Path(args.covariates)
    out_dir   = Path(args.out_dir)

    print("=" * 60)
    print("FIGURE 6 — FLIGHT COVARIATE × |MAE| CORRELATIONS")
    print("=" * 60)
    print(f"Predictions : {pred_path}")
    print(f"Covariates  : {cov_path}")
    print(f"Output      : {out_dir}\n")

    df = load_and_merge(pred_path, cov_path)

    # ── |MAE| analysis (primary figure) ─────────────────────────────────────
    print("\nSpearman ρ — |MAE| vs covariates")
    print("-" * 60)
    corr_mae = compute_spearman(df, "mae", COVARIATES_MAE)

    # ── Signed-error analysis (supplemental) ────────────────────────────────
    print("\nSpearman ρ — mean signed error vs covariates")
    print("-" * 60)
    corr_signed = compute_spearman(df, "mean_error", COVARIATES_SIGNED)

    # ── Save statistics table ────────────────────────────────────────────────
    corr_all = pd.concat(
        [corr_mae.assign(error_type="mae"),
         corr_signed.assign(error_type="mean_error")],
        ignore_index=True,
    )
    csv_path = out_dir / "fig06_flight_covariates_stats.csv"
    out_dir.mkdir(parents=True, exist_ok=True)
    corr_all.to_csv(csv_path, index=False, float_format="%.6f")
    print(f"\n[stats] saved → {csv_path}")

    # ── Figures ──────────────────────────────────────────────────────────────
    print("\nBuilding Figure 6 (|MAE| bar chart) …")
    plot_bar_chart(corr_mae, out_dir, "fig06_flight_covariates")

    print("\nBuilding supplemental scatter grid (|MAE|) …")
    plot_scatter_grid(df, corr_mae, "mae", out_dir,
                      "fig06_flight_covariates_scatter_mae", COVARIATES_MAE)

    print("\nBuilding supplemental scatter grid (signed error) …")
    plot_scatter_grid(df, corr_signed, "mean_error", out_dir,
                      "fig06_flight_covariates_scatter_signed", COVARIATES_SIGNED)

    print("\nBuilding supplemental statistics table …")
    save_supplemental_table(corr_mae, df, out_dir,
                            stem="tableS_flight_covariates")

    print("\nDone.")


if __name__ == "__main__":
    main()
